#!/usr/bin/env python3
"""
Assert the Grade Bench still predicts what the renderer produces.

WHY THIS IS THE MOST IMPORTANT TEST IN THE PROJECT
--------------------------------------------------
The Bench (bench/index.html) reimplements the grade in JavaScript so it can preview it at
interactive speed. The pipeline applies the real thing in ffmpeg. They are two implementations of
one transform, and the ENTIRE grading workflow rests on them agreeing: a person grades by eye in
the browser, sends the parameters, and the renderer applies them. If the two drift, the preview
silently stops predicting the render — no error, no warning, just a grade that looks right in the
Bench and wrong in the output, with nothing to point at.

WHAT CHANGED FROM THE CURVE-ONLY VERSION
----------------------------------------
This file used to compare the tone curve alone: the Bench's `curveAt` against a .cube generated by
make-tone-lut.py. That left the rest of the grade untested, and the rest of the grade is where the
Bench is WEAKEST — it approximates `hue=s=` with an RGB saturation about luma, and
`colorbalance=rm/bm` with a flat per-channel offset, applies them in the opposite order to the
renderer, and works in 8-bit. None of that is compared with anything yet.

This commit builds the instrument for that: a probe image, and a golden holding ffmpeg's own output
for it per parameter set. The curve check runs against it unchanged; the whole-grade comparison
arrives with the bench change that gives the Bench's per-pixel maths a name to extract.

FFMPEG IS THE ORACLE, and it is reached through `grade_chain` sourced out of scripts/lib.sh rather
than transcribed here. That is the point: this cannot drift from production, because it calls the
same builder production calls. The suite's "grade chain is built in exactly one place" test is what
keeps that true.

FRESHNESS IS BY CONTENT. The golden records a fingerprint of the chain string that produced it, and
a chain edit that outruns its golden fails BY NAME. mtime cannot work: git does not preserve it, so
on a fresh clone the committed golden always lands newer than lib.sh.

THE GOLDEN IS WRITTEN FROM HERE, not by a separate generator, so its format has exactly one home. A
reader and a writer in different files is the two-copies-one-edited failure this project keeps
finding.

Usage:
  tests/grade-parity.py               assert against the committed golden (needs node)
  tests/grade-parity.py --regenerate  re-render the probe and the golden (needs ffmpeg)
"""
import hashlib
import json
import os
import re
import struct
import subprocess
import sys
import tempfile
import zlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BENCH = os.path.join(ROOT, "bench", "index.html")
GEN = os.path.join(ROOT, "scripts", "make-tone-lut.py")
LIB = os.path.join(ROOT, "scripts", "lib.sh")
FIXTURES = os.path.join(ROOT, "tests", "fixtures")
PROBE = os.path.join(FIXTURES, "grade-probe.png")
GOLDEN = os.path.join(FIXTURES, "grade-golden.json")

# Two calibration runs, then the shipped look, then the corners — a divergence is most likely to
# hide in a branch the shipped values never take, which is why the extremes are here at all.
#
# NEITHER CALIBRATION RUN IS A LOOK. Both neutralise the curve, the saturation and the warmth, and
# they differ only in which 3D LUT sits at the head of the chain:
#
#   floor      an identity cube. What this moves is the RGB/YUV round-trip ffmpeg performs either
#              side of the chain — error that belongs to colour conversion, not to anyone's maths.
#              Every other number here has to be read on top of it.
#   post-look  the real Portra cube. This is the Bench's documented input (post-CST, post-look), so
#              it is what the Bench's own maths will be fed once there is a function to extract.
#
# The first version of this file used one run for both jobs and reported a 189-code-value "floor",
# which was the look LUT's own effect rather than any conversion error. Two runs, two questions.
CASES = [
    ("floor", dict(gamma=1.00, pivot=0.50, contrast=1.00, toe=0.00, shoulder=0.00, black=0.000),
     1.00, 0.000, "identity"),
    ("post-look", dict(gamma=1.00, pivot=0.50, contrast=1.00, toe=0.00, shoulder=0.00, black=0.000),
     1.00, 0.000, "real"),
    # The shipped look, then the same look split in half, so the divergence can be attributed
    # rather than just reported. `tone-only` moves the curve with the trims neutral, which isolates
    # the curve's APPLICATION — ffmpeg curves the Y plane in YUV, the Bench curves an RGB-derived
    # luma in full range. `trims-only` moves saturation and warmth with the curve neutral, which
    # isolates hue=s= against an RGB saturation and colorbalance against a flat offset.
    ("shipped", dict(gamma=2.02, pivot=0.39, contrast=1.09, toe=0.00, shoulder=0.10, black=0.025),
     1.27, 0.005, "real"),
    ("tone-only", dict(gamma=2.02, pivot=0.39, contrast=1.09, toe=0.00, shoulder=0.10, black=0.025),
     1.00, 0.000, "real"),
    ("trims-only", dict(gamma=1.00, pivot=0.50, contrast=1.00, toe=0.00, shoulder=0.00,
                        black=0.000), 1.27, 0.005, "real"),
    ("extreme", dict(gamma=2.60, pivot=0.25, contrast=1.80, toe=0.80, shoulder=0.80, black=0.080),
     1.60, 0.120, "real"),
    ("negative-black", dict(gamma=1.50, pivot=0.65, contrast=0.80, toe=0.40, shoulder=0.00,
                            black=-0.080), 0.60, -0.120, "real"),
    ("midrange", dict(gamma=1.85, pivot=0.45, contrast=1.12, toe=0.30, shoulder=0.35, black=0.000),
     1.12, 0.000, "real"),
]
CALIBRATION = ("floor", "post-look")

# One 8-bit code value: below this nothing downstream can see it. This is the bar the CURVE has
# always met and must keep meeting. The whole-grade tolerance is not a choice — it is measured, and
# it lives in the golden beside the number it describes.
CURVE_TOLERANCE = 1.0 / 255.0

# --- the probe ----------------------------------------------------------------
# Patches rather than a photograph, because a photograph's coverage is whatever happened to be in
# frame. Three groups, each answering a different question:
#
#   cube    a 5-step grid over the RGB cube. Coarse deliberately: the trims are smooth functions
#           of colour, so a denser grid would cost golden size without adding a failure mode.
#   ramp    256 neutral steps. The tone curve lives here, and the curve is the part with branches
#           in it, so it gets the dense coverage.
#   refs    the four references the Bench measures, taken from its own SAMPLERS swatches rather
#           than invented here: RAL 1021 plate yellow, RAL 3020 traffic red, RAL 5017 traffic blue
#           and a near-neutral. Saturated colour is where a per-channel trim misbehaves.
CUBE_STEPS = 5
RAMP_STEPS = 256
REFS = [(0xf3, 0xc3, 0x00), (0xcc, 0x06, 0x05), (0x06, 0x39, 0x71), (0x8b, 0x8f, 0x96)]
PATCH = 4          # pixels per patch side; the reader samples the centre
GRID_W = 20        # patches per row


def probe_patches():
    """The probe's patch values, 16-bit, in layout order. One source of truth for both the image
    and the golden's input column."""
    out = []
    q = CUBE_STEPS - 1
    for r in range(CUBE_STEPS):
        for g in range(CUBE_STEPS):
            for b in range(CUBE_STEPS):
                out.append(tuple(int(round(c * 65535 / q)) for c in (r, g, b)))
    for i in range(RAMP_STEPS):
        v = int(round(i * 65535 / (RAMP_STEPS - 1)))
        out.append((v, v, v))
    for r, g, b in REFS:
        out.append(tuple(int(round(c * 65535 / 255)) for c in (r, g, b)))
    return out


def probe_size(n):
    rows = (n + GRID_W - 1) // GRID_W
    return GRID_W * PATCH, rows * PATCH


def probe_png_bytes():
    """A 16-bit PNG, written here rather than through ffmpeg so the probe carries no swscale
    behaviour of its own — what is being measured must not also be in the ruler."""
    patches = probe_patches()
    w, h = probe_size(len(patches))
    rows = []
    for y in range(h):
        row = bytearray(b"\x00")           # filter type 0
        for x in range(w):
            i = (y // PATCH) * GRID_W + (x // PATCH)
            r, g, b = patches[i] if i < len(patches) else (0, 0, 0)
            row += struct.pack(">HHH", r, g, b)
        rows.append(bytes(row))

    def chunk(tag, data):
        return (struct.pack(">I", len(data)) + tag + data
                + struct.pack(">I", zlib.crc32(tag + data) & 0xffffffff))

    ihdr = struct.pack(">IIBBBBB", w, h, 16, 2, 0, 0, 0)
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
            + chunk(b"IDAT", zlib.compress(b"".join(rows), 9)) + chunk(b"IEND", b""))


def sample_offsets(n):
    """Byte offset of each patch's centre pixel within an rgb48le raw frame."""
    w, _ = probe_size(n)
    off = []
    for i in range(n):
        px = (i % GRID_W) * PATCH + PATCH // 2
        py = (i // GRID_W) * PATCH + PATCH // 2
        off.append((py * w + px) * 6)
    return off


# --- the chain, out of lib.sh -------------------------------------------------
def chain_string(tone, sat, warm, look=""):
    """The production chain, out of lib.sh. `look` overrides LOOK_LUT *after* sourcing, which is
    how the floor run swaps the Portra cube for an identity one without this file transcribing a
    single filter."""
    r = subprocess.run(["bash", "-c",
                        'set -euo pipefail; source "$1"; [ -z "$5" ] || LOOK_LUT="$5"; '
                        'grade_chain "$2" "$3" "$4"',
                        "_", LIB, tone, sat, warm, look],
                       capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit("could not read grade_chain out of lib.sh:\n" + r.stderr)
    return r.stdout.strip()


def identity_cube(path):
    """A 3D LUT that maps every corner to itself. Interpolating it is exact, so the floor run
    measures conversion and nothing else."""
    with open(path, "w") as f:
        f.write("TITLE \"identity\"\nLUT_3D_SIZE 2\n")
        for b in (0, 1):
            for g in (0, 1):
                for r in (0, 1):
                    f.write("%d %d %d\n" % (r, g, b))


def chain_fingerprint():
    """Hash the chain's SHAPE, with the parameters and the absolute LUT path tokenised out. The
    look LUT's path contains the checkout location, so hashing it raw would make every clone
    disagree, and the parameters vary per case and are recorded separately anyway."""
    s = chain_string("<TONE>", "<SAT>", "<WARM>").replace(ROOT, "<ROOT>")
    return hashlib.sha256(s.encode("utf-8")).hexdigest()


# --- ffmpeg, the oracle -------------------------------------------------------
def render_case(params, sat, warm, probe_path, look="real"):
    with tempfile.NamedTemporaryFile(suffix=".cube", delete=False) as f:
        cube = f.name
    ident = None
    if look == "identity":
        with tempfile.NamedTemporaryFile(suffix=".cube", delete=False) as f:
            ident = f.name
        identity_cube(ident)
    try:
        cmd = [sys.executable, GEN, cube]
        for k, v in params.items():
            cmd += ["--" + k, str(v)]
        r = subprocess.run(cmd, capture_output=True, text=True)
        if r.returncode != 0:
            sys.exit("make-tone-lut.py failed:\n" + r.stderr)
        graph = "[0:v]%s,format=rgb48le[o]" % chain_string(cube, str(sat), str(warm), ident or "")
        r = subprocess.run(["ffmpeg", "-v", "error", "-i", probe_path,
                            "-filter_complex", graph, "-map", "[o]",
                            "-f", "rawvideo", "-pix_fmt", "rgb48le", "-"],
                           capture_output=True)
        if r.returncode != 0:
            sys.exit("ffmpeg failed on the probe:\n" + r.stderr.decode("utf-8", "replace"))
        raw = r.stdout
        return [list(struct.unpack_from("<HHH", raw, off))
                for off in sample_offsets(len(probe_patches()))]
    finally:
        os.unlink(cube)
        if ident:
            os.unlink(ident)


# --- the javascript side ------------------------------------------------------
def extract_js(names):
    """Pull functions out of the Bench verbatim, brace-walking from each declaration. This compares
    BEHAVIOUR rather than source, so a stylistic edit does not fail the run — but it does depend on
    each one staying a `function NAME(` declaration that reads P as a free variable."""
    src = open(BENCH, encoding="utf-8").read()
    out = []
    for name in names:
        m = re.search(r"function\s+%s\s*\(" % name, src)
        if not m:
            sys.exit("could not find function %s() in %s" % (name, BENCH))
        start = src.index("{", m.end() - 1)
        depth, i = 0, start
        while i < len(src):
            if src[i] == "{":
                depth += 1
            elif src[i] == "}":
                depth -= 1
                if depth == 0:
                    break
            i += 1
        out.append(src[m.start():i + 1])
    return "\n".join(out)


def run_node(harness):
    with tempfile.NamedTemporaryFile("w", suffix=".js", delete=False) as f:
        f.write(harness)
        path = f.name
    try:
        r = subprocess.run(["node", path], capture_output=True, text=True)
        if r.returncode != 0:
            sys.exit("node failed:\n" + r.stderr)
        return json.loads(r.stdout)
    finally:
        os.unlink(path)


def js_curve(params, xs):
    return run_node("""
%s
var P = %s;
var out = %s.map(function (x) { return curveAt(x); });
console.log(JSON.stringify(out));
""" % (extract_js(("soft", "curveAt")), json.dumps(params), json.dumps(xs)))



def py_curve(params, xs):
    """Generate a real .cube and read the curve back out of it, so the .cube writer is covered
    rather than just the formula."""
    with tempfile.NamedTemporaryFile(suffix=".cube", delete=False) as f:
        cube = f.name
    try:
        cmd = [sys.executable, GEN, cube]
        for k, v in params.items():
            cmd += ["--" + k, str(v)]
        r = subprocess.run(cmd, capture_output=True, text=True)
        if r.returncode != 0:
            sys.exit("make-tone-lut.py failed:\n" + r.stderr)
        vals = []
        for line in open(cube):
            s = line.strip()
            if not s or s.startswith("#") or s.startswith("TITLE") or s.startswith("LUT_"):
                continue
            q = s.split()
            if len(q) == 3:
                vals.append(float(q[0]))
        n = len(vals)
        return [vals[min(n - 1, int(round(x * (n - 1))))] for x in xs]
    finally:
        os.unlink(cube)


def to8(v):
    return [c * 255.0 / 65535.0 for c in v]


def worst_delta(js, ff):
    w = 0.0
    for a, b in zip(js, ff):
        for x, y in zip(a, b):
            w = max(w, abs(x - y))
    return w


# --- regenerate ---------------------------------------------------------------
def regenerate():
    if not os.path.isdir(FIXTURES):
        os.makedirs(FIXTURES)
    png = probe_png_bytes()
    open(PROBE, "wb").write(png)
    patches = probe_patches()
    w, h = probe_size(len(patches))
    print("probe   %dx%d, %d patches, %d bytes" % (w, h, len(patches), len(png)))

    cases = []
    for name, params, sat, warm, look in CASES:
        out = render_case(params, sat, warm, PROBE, look)
        cases.append(dict(name=name, params=params, saturation=sat, warmth=warm,
                          look=look, output=out))
        print("render  %-15s %d samples (%s look LUT)" % (name, len(out), look))

    by = {c["name"]: c for c in cases}
    floor = worst_delta([to8(v) for v in by["floor"]["output"]], [to8(v) for v in patches])

    golden = {
        "_comment": [
            "Generated by tests/grade-parity.py --regenerate. Do not hand-edit: the harness that",
            "reads this file is the one that writes it, so an edited value is a claim nothing",
            "produced.",
            "",
            "chain_fingerprint hashes grade_chain's SHAPE, with the parameters and the checkout",
            "path tokenised out. It is how freshness is decided: a chain edit that outruns this",
            "file fails by name. mtime cannot work, because git does not preserve it.",
            "",
            "output holds ffmpeg's own result per probe patch, 16-bit RGB. That is what makes",
            "ffmpeg the oracle rather than anyone's transcription of it.",
        ],
        "chain_fingerprint": chain_fingerprint(),
        "probe": {
            "sha256": hashlib.sha256(png).hexdigest(),
            "patch": PATCH, "grid_w": GRID_W,
            "cube_steps": CUBE_STEPS, "ramp_steps": RAMP_STEPS, "refs": len(REFS),
        },
        "tolerances": {
            "curve_code_values": 1.0,
            "_curve_why": [
                "One 8-bit code value, the bar the curve has always met: below it nothing",
                "downstream can see the difference.",
            ],
            "conversion_floor_code_values": round(floor, 3),
            "_floor_why": [
                "What the `floor` case moves: identity look cube, identity curve, saturation 1,",
                "warmth 0. So this is the RGB/YUV round-trip ffmpeg performs either side of the",
                "chain, not anyone's maths, and every other number here has to be read on top of",
                "it. Measured with two separate runs because measuring it with one — the real look",
                "cube and a neutral curve — reported the look LUT's own effect as a 189-code-value",
                "conversion error.",
            ],
        },
        "cases": cases,
    }
    with open(GOLDEN, "w") as f:
        json.dump(golden, f, indent=1)
        f.write("\n")
    print("\nfloor   %.3f code values (RGB/YUV round-trip)" % floor)
    print("wrote   %s (%d bytes)" % (os.path.relpath(GOLDEN, ROOT), os.path.getsize(GOLDEN)))


# --- check --------------------------------------------------------------------
def check():
    if not os.path.exists(GOLDEN):
        sys.exit("no golden at %s — run tests/grade-parity.py --regenerate" % GOLDEN)
    golden = json.load(open(GOLDEN))
    fails = []

    # 1. Freshness, by content: the guard that stops a chain edit shipping with a golden that
    #    describes the chain it replaced.
    now = chain_fingerprint()
    if now != golden["chain_fingerprint"]:
        print("STALE GOLDEN\n"
              "  grade_chain in scripts/lib.sh no longer matches the chain this golden was\n"
              "  generated from.\n    golden: %s\n    lib.sh: %s\n"
              "  If the change was intended, re-run tests/grade-parity.py --regenerate and say in\n"
              "  the commit what moved and why." % (golden["chain_fingerprint"][:16], now[:16]),
              file=sys.stderr)
        return 1

    # 2. The probe itself, by content, for the same reason.
    if os.path.exists(PROBE):
        have = hashlib.sha256(open(PROBE, "rb").read()).hexdigest()
        if have != golden["probe"]["sha256"]:
            print("the probe image does not match the golden measured on it", file=sys.stderr)
            return 1

    # 3. The curve on its own, so a curve drift is pinned to the curve rather than to the grade.
    xs = [i / 256.0 for i in range(257)]
    for name, params, _sat, _warm, _look in CASES:
        j, p = js_curve(params, xs), py_curve(params, xs)
        worst = max(abs(a - b) for a, b in zip(j, p))
        if worst > CURVE_TOLERANCE:
            fails.append("curve %s: max delta %.5f > %.5f" % (name, worst, CURVE_TOLERANCE))
            print("DRIFTED  curve %-15s max delta %.5f" % (name, worst))
        else:
            print("in step  curve %-15s max delta %.6f" % (name, worst))

    if fails:
        print("\nThe Bench and the renderer have diverged. The browser preview no longer predicts\n"
              "what ffmpeg produces, so any grade sent from it is unreliable until they are\n"
              "reconciled. Fix BOTH, then re-run.\n  " + "\n  ".join(fails), file=sys.stderr)
        return 1
    print("\nCurve within %.5f. Probe and golden fresh; floor %.3f code values."
          % (CURVE_TOLERANCE, golden["tolerances"]["conversion_floor_code_values"]))
    return 0


if __name__ == "__main__":
    if "--regenerate" in sys.argv[1:]:
        regenerate()
        sys.exit(0)
    sys.exit(check())
