#!/usr/bin/env python3
"""
Assert the Grade Bench still predicts what the renderer produces.

WHY THIS IS THE MOST IMPORTANT TEST IN THE PROJECT
--------------------------------------------------
The Bench (bench/index.html) reimplements the grade in JavaScript so it can preview it at
interactive speed. The pipeline applies the real thing in ffmpeg. They are two implementations of
one transform, and the ENTIRE grading workflow rests on them agreeing: a person grades by eye in
the browser, sends the parameters, and the renderer applies them. If the two drift, the preview
silently stops predicting the render — no error, no warning, just a grade that looks right in the
Bench and wrong in the output, with nothing to point at.

WHAT CHANGED FROM THE CURVE-ONLY VERSION
----------------------------------------
This file used to compare the tone curve alone: the Bench's `curveAt` against a .cube generated by
make-tone-lut.py. That left the rest of the grade untested, and the rest of the grade is where the
Bench is WEAKEST — it approximates `hue=s=` with an RGB saturation about luma, and
`colorbalance=rm/bm` with a flat per-channel offset, applies them in the opposite order to the
renderer, and works in 8-bit. None of that was compared with anything. So this asserts at two
levels now:

  1. the curve, exactly as before — JS `curveAt` against the generated .cube, so the .cube writer
     is covered and a curve drift is pinned to the curve rather than to the whole grade;
  2. the whole grade — JS `gradePixel` against ffmpeg's own output over a probe image.

FFMPEG IS THE ORACLE, and it is reached through `grade_chain` sourced out of scripts/lib.sh rather
than transcribed here. That is the point: this cannot drift from production, because it calls the
same builder production calls. The suite's "grade chain is built in exactly one place" test is what
keeps that true.

WHERE THE DIVERGENCE COMES FROM, AND WHAT IT IS NOT
--------------------------------------------------
The whole-grade numbers below are dominated by the tone case at roughly 36 code values, and an
attempt to fix that in the Bench failed usefully. Six models were fitted against ffmpeg's own
recorded output over this probe, and none of these is the cause:

  - the SPACE. Rewriting the Bench to convert to luma and chroma, curve the luma, and clip once at
    the end changes nothing at all: adding one luma delta to R, G and B is algebraically identical
    to curving Y while holding Cb and Cr, because the channel differences are preserved either way.
  - the CLIPPING POINT. Same reason. Both clip each channel to 0..255 in the end.
  - the ORDER. Moving saturation ahead of warmth, which is the renderer's order, moves the trims
    case from 6.31 to 5.35 and leaves the tone case untouched.
  - the MATRIX. 709 fits better than 601 (35.75 against 39.01) and better than 2020. So the
    conversion is 709, as tagged.
  - the RANGE. Full range fits at 35.75 against 46.50 for limited, which corroborates the ramp
    measurement independently.
  - WHICH PLANE IS CURVED. Curving chroma instead of luma is far worse, 117 against 36, so
    mergeplanes does map the way its documentation says.

What is left, and what the next attempt should test, is that ffmpeg's YUV intermediate clamps
out-of-gamut colour in YUV rather than in RGB. The worst patches are all at saturation extremes —
the worst is a near-primary orange, 246.8/48.7/5.0 in, where the Bench produces 187.7/0.0/0.0 and
ffmpeg 223.9/25.8/0.0 — and a synthetic cube probe samples those corners deliberately. Real
footage reaches them on signage, which is the one place it would be visible.

One thing the same experiment settled positively: ffmpeg's colorbalance is level-weighted, not a
flat offset. Weighting warmth by the midtone ramp moves the warm-only case from 31.6 to 22.4 code
values, and the Bench's flat offset is wrong everywhere except the midtones. It is not committed,
because the same change moves negative-black the wrong way, from 36.4 to 40.4 — the weighting is
evidently not symmetric in the sign of the move, and guessing again without reading ffmpeg's source
would be another round of this.

WHAT THIS DOES NOT COVER YET. The input-correction stage (scripts/make-correct-lut.py) has no
counterpart in the Bench, so there is nothing to compare it against here. When the app's preview
implements it, it gets a case of its own — and the probe has to become an Apple Log probe, because
that stage runs before the conversion and a Rec.709 probe cannot exercise it.

FRESHNESS IS BY CONTENT. The golden records a fingerprint of the chain string that produced it, and
a chain edit that outruns its golden fails BY NAME. mtime cannot work: git does not preserve it, so
on a fresh clone the committed golden always lands newer than lib.sh.

THE GOLDEN IS WRITTEN FROM HERE, not by a separate generator, so its format has exactly one home. A
reader and a writer in different files is the two-copies-one-edited failure this project keeps
finding.

Usage:
  tests/grade-parity.py               assert against the committed golden (needs node)
  tests/grade-parity.py --regenerate  re-render the probe and the golden (needs ffmpeg)
"""
import hashlib
import json
import os
import re
import struct
import subprocess
import sys
import tempfile
import zlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BENCH = os.path.join(ROOT, "bench", "index.html")
GEN = os.path.join(ROOT, "scripts", "make-tone-lut.py")
LIB = os.path.join(ROOT, "scripts", "lib.sh")
FIXTURES = os.path.join(ROOT, "tests", "fixtures")
PROBE = os.path.join(FIXTURES, "grade-probe.png")
GOLDEN = os.path.join(FIXTURES, "grade-golden.json")

# Two calibration runs, then the shipped look, then the corners — a divergence is most likely to
# hide in a branch the shipped values never take, which is why the extremes are here at all.
#
# NEITHER CALIBRATION RUN IS A LOOK. Both neutralise the curve, the saturation and the warmth, and
# they differ only in which 3D LUT sits at the head of the chain:
#
#   floor      no look filter at all. What this moves is the RGB/YUV round-trip ffmpeg performs
#              side of the chain — error that belongs to colour conversion, not to anyone's maths.
#              Every other number here has to be read on top of it.
#   post-look  the real Portra cube. This is the Bench's documented input (post-CST, post-look), so
#              it is what the Bench's own maths gets fed in the comparison below.
#
# The first version of this file used one run for both jobs and reported a 189-code-value "floor",
# which was the look LUT's own effect rather than any conversion error. Two runs, two questions.
CASES = [
    ("floor", dict(gamma=1.00, pivot=0.50, contrast=1.00, toe=0.00, shoulder=0.00, black=0.000),
     1.00, 0.000, "none"),
    ("post-look", dict(gamma=1.00, pivot=0.50, contrast=1.00, toe=0.00, shoulder=0.00, black=0.000),
     1.00, 0.000, "real"),
    # The shipped look, then the same look split in half, so the divergence can be attributed
    # rather than just reported. `tone-only` moves the curve with the trims neutral, which isolates
    # the curve's APPLICATION — ffmpeg curves the Y plane in YUV, the Bench curves an RGB-derived
    # luma in full range. `trims-only` moves saturation and warmth with the curve neutral, which
    # isolates hue=s= against an RGB saturation and colorbalance against a flat offset.
    ("shipped", dict(gamma=2.02, pivot=0.39, contrast=1.09, toe=0.00, shoulder=0.10, black=0.025),
     1.27, 0.005, "real"),
    ("tone-only", dict(gamma=2.02, pivot=0.39, contrast=1.09, toe=0.00, shoulder=0.10, black=0.025),
     1.00, 0.000, "real"),
    ("trims-only", dict(gamma=1.00, pivot=0.50, contrast=1.00, toe=0.00, shoulder=0.00,
                        black=0.000), 1.27, 0.005, "real"),
    # One trim each, at a value large enough to see on its own. Without these the guard is
    # insensitive to a small trim regression: the shipped look's divergence is dominated by the
    # tone stage, so deleting the Bench's warmth line entirely hid underneath it and left
    # `shipped` green. Found by mutation.
    ("warm-only", dict(gamma=1.00, pivot=0.50, contrast=1.00, toe=0.00, shoulder=0.00,
                       black=0.000), 1.00, 0.120, "real"),
    ("sat-only", dict(gamma=1.00, pivot=0.50, contrast=1.00, toe=0.00, shoulder=0.00,
                      black=0.000), 1.60, 0.000, "real"),
    ("extreme", dict(gamma=2.60, pivot=0.25, contrast=1.80, toe=0.80, shoulder=0.80, black=0.080),
     1.60, 0.120, "real"),
    ("negative-black", dict(gamma=1.50, pivot=0.65, contrast=0.80, toe=0.40, shoulder=0.00,
                            black=-0.080), 0.60, -0.120, "real"),
    ("midrange", dict(gamma=1.85, pivot=0.45, contrast=1.12, toe=0.30, shoulder=0.35, black=0.000),
     1.12, 0.000, "real"),
]
CALIBRATION = ("floor", "post-look")

# One 8-bit code value: below this nothing downstream can see it. This is the bar the CURVE has
# always met and must keep meeting. The whole-grade tolerance is not a choice — it is measured, and
# it lives in the golden beside the number it describes.
CURVE_TOLERANCE = 1.0 / 255.0

# --- the probe ----------------------------------------------------------------
# Patches rather than a photograph, because a photograph's coverage is whatever happened to be in
# frame. Three groups, each answering a different question:
#
#   cube    a 5-step grid over the RGB cube. Coarse deliberately: the trims are smooth functions
#           of colour, so a denser grid would cost golden size without adding a failure mode.
#   ramp    256 neutral steps. The tone curve lives here, and the curve is the part with branches
#           in it, so it gets the dense coverage.
#   refs    the four references the Bench measures, taken from its own SAMPLERS swatches rather
#           than invented here: RAL 1021 plate yellow, RAL 3020 traffic red, RAL 5017 traffic blue
#           and a near-neutral. Saturated colour is where a per-channel trim misbehaves.
CUBE_STEPS = 5
RAMP_STEPS = 256
REFS = [(0xf3, 0xc3, 0x00), (0xcc, 0x06, 0x05), (0x06, 0x39, 0x71), (0x8b, 0x8f, 0x96)]
PATCH = 4          # pixels per patch side; the reader samples the centre
GRID_W = 20        # patches per row


def probe_patches():
    """The probe's patch values, 16-bit, in layout order. One source of truth for both the image
    and the golden's input column."""
    out = []
    q = CUBE_STEPS - 1
    for r in range(CUBE_STEPS):
        for g in range(CUBE_STEPS):
            for b in range(CUBE_STEPS):
                out.append(tuple(int(round(c * 65535 / q)) for c in (r, g, b)))
    for i in range(RAMP_STEPS):
        v = int(round(i * 65535 / (RAMP_STEPS - 1)))
        out.append((v, v, v))
    for r, g, b in REFS:
        out.append(tuple(int(round(c * 65535 / 255)) for c in (r, g, b)))
    return out


def probe_size(n):
    rows = (n + GRID_W - 1) // GRID_W
    return GRID_W * PATCH, rows * PATCH


def probe_png_bytes():
    """A 16-bit PNG, written here rather than through ffmpeg so the probe carries no swscale
    behaviour of its own — what is being measured must not also be in the ruler."""
    patches = probe_patches()
    w, h = probe_size(len(patches))
    rows = []
    for y in range(h):
        row = bytearray(b"\x00")           # filter type 0
        for x in range(w):
            i = (y // PATCH) * GRID_W + (x // PATCH)
            r, g, b = patches[i] if i < len(patches) else (0, 0, 0)
            row += struct.pack(">HHH", r, g, b)
        rows.append(bytes(row))

    def chunk(tag, data):
        return (struct.pack(">I", len(data)) + tag + data
                + struct.pack(">I", zlib.crc32(tag + data) & 0xffffffff))

    ihdr = struct.pack(">IIBBBBB", w, h, 16, 2, 0, 0, 0)
    return (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
            + chunk(b"IDAT", zlib.compress(b"".join(rows), 9)) + chunk(b"IEND", b""))


def sample_offsets(n):
    """Byte offset of each patch's centre pixel within an rgb48le raw frame."""
    w, _ = probe_size(n)
    off = []
    for i in range(n):
        px = (i % GRID_W) * PATCH + PATCH // 2
        py = (i // GRID_W) * PATCH + PATCH // 2
        off.append((py * w + px) * 6)
    return off


# --- the chain, out of lib.sh -------------------------------------------------
def chain_string(tone, sat, warm, look="real"):
    """The production chain, out of lib.sh.

    `look` is "real" for look.json's own choice, or anything resolve_look_lut accepts — "none"
    being the one the floor run uses. It has to be resolved the way the entry scripts resolve it,
    because lib.sh stopped setting LOOK_LUT when the look stopped being a constant: sourcing it and
    calling grade_chain therefore emits a chain with NO look filter at all. The fingerprint guard
    is what caught that, which is the whole reason it hashes the chain rather than trusting it."""
    r = subprocess.run(["bash", "-c",
                        'set -euo pipefail; source "$1"; '
                        'if [ "$5" = "real" ]; then '
                        '  LOOK_LUT="$(resolve_look_lut "$(look .look.lut)" "$6")"; '
                        'else LOOK_LUT="$(resolve_look_lut "$5" "$6")"; fi; '
                        'grade_chain "$2" "$3" "$4"',
                        "_", LIB, tone, sat, warm, look, ROOT],
                       capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit("could not read grade_chain out of lib.sh:\n" + r.stderr)
    return r.stdout.strip()


def chain_fingerprint():
    """Hash the chain's SHAPE, with the parameters and the absolute LUT path tokenised out. The
    look LUT's path contains the checkout location, so hashing it raw would make every clone
    disagree, and the parameters vary per case and are recorded separately anyway."""
    s = chain_string("<TONE>", "<SAT>", "<WARM>", "real").replace(ROOT, "<ROOT>")
    return hashlib.sha256(s.encode("utf-8")).hexdigest()


# --- ffmpeg, the oracle -------------------------------------------------------
def render_case(params, sat, warm, probe_path, look="real"):
    with tempfile.NamedTemporaryFile(suffix=".cube", delete=False) as f:
        cube = f.name
    # "none" omits the look filter rather than interpolating an identity cube through it, which is
    # what the engine itself now does — and it measures the round trip without a lookup in it at
    # all, which is what this case was always trying to isolate.
    try:
        cmd = [sys.executable, GEN, cube]
        for k, v in params.items():
            cmd += ["--" + k, str(v)]
        r = subprocess.run(cmd, capture_output=True, text=True)
        if r.returncode != 0:
            sys.exit("make-tone-lut.py failed:\n" + r.stderr)
        graph = "[0:v]%s,format=rgb48le[o]" % chain_string(cube, str(sat), str(warm), look)
        r = subprocess.run(["ffmpeg", "-v", "error", "-i", probe_path,
                            "-filter_complex", graph, "-map", "[o]",
                            "-f", "rawvideo", "-pix_fmt", "rgb48le", "-"],
                           capture_output=True)
        if r.returncode != 0:
            sys.exit("ffmpeg failed on the probe:\n" + r.stderr.decode("utf-8", "replace"))
        raw = r.stdout
        return [list(struct.unpack_from("<HHH", raw, off))
                for off in sample_offsets(len(probe_patches()))]
    finally:
        os.unlink(cube)


# --- the javascript side ------------------------------------------------------
def extract_js(names):
    """Pull functions out of the Bench verbatim, brace-walking from each declaration. This compares
    BEHAVIOUR rather than source, so a stylistic edit does not fail the run — but it does depend on
    each one staying a `function NAME(` declaration that reads P as a free variable."""
    src = open(BENCH, encoding="utf-8").read()
    out = []
    for name in names:
        m = re.search(r"function\s+%s\s*\(" % name, src)
        if not m:
            sys.exit("could not find function %s() in %s" % (name, BENCH))
        start = src.index("{", m.end() - 1)
        depth, i = 0, start
        while i < len(src):
            if src[i] == "{":
                depth += 1
            elif src[i] == "}":
                depth -= 1
                if depth == 0:
                    break
            i += 1
        out.append(src[m.start():i + 1])
    return "\n".join(out)


def run_node(harness):
    with tempfile.NamedTemporaryFile("w", suffix=".js", delete=False) as f:
        f.write(harness)
        path = f.name
    try:
        r = subprocess.run(["node", path], capture_output=True, text=True)
        if r.returncode != 0:
            sys.exit("node failed:\n" + r.stderr)
        return json.loads(r.stdout)
    finally:
        os.unlink(path)


def js_curve(params, xs):
    return run_node("""
%s
var P = %s;
var out = %s.map(function (x) { return curveAt(x); });
console.log(JSON.stringify(out));
""" % (extract_js(("soft", "curveAt")), json.dumps(params), json.dumps(xs)))


def js_grade(params, sat, warm, inputs8):
    """Run the Bench's own per-pixel grade over 8-bit inputs, which is the space it works in."""
    p = dict(params)
    p["sat"] = sat
    p["warm"] = warm
    return run_node("""
%s
var P = %s;
var lut = new Float32Array(256);
for (var k = 0; k < 256; k++) lut[k] = curveAt(k / 255) * 255;
var px = [0, 0, 0];
var out = %s.map(function (p) {
  gradePixel(p[0], p[1], p[2], lut, px);
  return [px[0], px[1], px[2]];
});
console.log(JSON.stringify(out));
""" % (extract_js(("soft", "curveAt", "gradePixel")), json.dumps(p), json.dumps(inputs8)))


def py_curve(params, xs):
    """Generate a real .cube and read the curve back out of it, so the .cube writer is covered
    rather than just the formula."""
    with tempfile.NamedTemporaryFile(suffix=".cube", delete=False) as f:
        cube = f.name
    try:
        cmd = [sys.executable, GEN, cube]
        for k, v in params.items():
            cmd += ["--" + k, str(v)]
        r = subprocess.run(cmd, capture_output=True, text=True)
        if r.returncode != 0:
            sys.exit("make-tone-lut.py failed:\n" + r.stderr)
        vals = []
        for line in open(cube):
            s = line.strip()
            if not s or s.startswith("#") or s.startswith("TITLE") or s.startswith("LUT_"):
                continue
            q = s.split()
            if len(q) == 3:
                vals.append(float(q[0]))
        n = len(vals)
        return [vals[min(n - 1, int(round(x * (n - 1))))] for x in xs]
    finally:
        os.unlink(cube)


def to8(v):
    return [c * 255.0 / 65535.0 for c in v]


def worst_delta(js, ff):
    w = 0.0
    for a, b in zip(js, ff):
        for x, y in zip(a, b):
            w = max(w, abs(x - y))
    return w


# --- regenerate ---------------------------------------------------------------
def regenerate():
    if not os.path.isdir(FIXTURES):
        os.makedirs(FIXTURES)
    png = probe_png_bytes()
    open(PROBE, "wb").write(png)
    patches = probe_patches()
    w, h = probe_size(len(patches))
    print("probe   %dx%d, %d patches, %d bytes" % (w, h, len(patches), len(png)))

    cases = []
    for name, params, sat, warm, look in CASES:
        out = render_case(params, sat, warm, PROBE, look)
        cases.append(dict(name=name, params=params, saturation=sat, warmth=warm,
                          look=look, output=out))
        print("render  %-15s %d samples (%s look LUT)" % (name, len(out), look))

    by = {c["name"]: c for c in cases}
    base = by["post-look"]["output"]
    ins = [[round(x, 4) for x in to8(v)] for v in base]
    worst = {}
    for c in cases:
        if c["name"] in CALIBRATION:
            continue
        js = js_grade(c["params"], c["saturation"], c["warmth"], ins)
        d = worst_delta(js, [to8(v) for v in c["output"]])
        worst[c["name"]] = round(d, 3)
        print("measure %-15s worst |JS - ffmpeg| = %.3f code values" % (c["name"], d))

    floor = worst_delta([to8(v) for v in by["floor"]["output"]], [to8(v) for v in patches])

    golden = {
        "_comment": [
            "Generated by tests/grade-parity.py --regenerate. Do not hand-edit: the harness that",
            "reads this file is the one that writes it, so an edited value is a claim nothing",
            "produced.",
            "",
            "chain_fingerprint hashes grade_chain's SHAPE, with the parameters and the checkout",
            "path tokenised out. It is how freshness is decided: a chain edit that outruns this",
            "file fails by name. mtime cannot work, because git does not preserve it.",
            "",
            "output holds ffmpeg's own result per probe patch, 16-bit RGB. That is what makes",
            "ffmpeg the oracle rather than anyone's transcription of it.",
        ],
        "chain_fingerprint": chain_fingerprint(),
        "probe": {
            "sha256": hashlib.sha256(png).hexdigest(),
            "patch": PATCH, "grid_w": GRID_W,
            "cube_steps": CUBE_STEPS, "ramp_steps": RAMP_STEPS, "refs": len(REFS),
        },
        "tolerances": {
            "curve_code_values": 1.0,
            "_curve_why": [
                "One 8-bit code value, the bar the curve has always met: below it nothing",
                "downstream can see the difference.",
            ],
            "conversion_floor_code_values": round(floor, 3),
            "_floor_why": [
                "What the `floor` case moves: identity look cube, identity curve, saturation 1,",
                "warmth 0. So this is the RGB/YUV round-trip ffmpeg performs either side of the",
                "chain, not anyone's maths, and every other number here has to be read on top of",
                "it. Measured with two separate runs because measuring it with one — the real look",
                "cube and a neutral curve — reported the look LUT's own effect as a 189-code-value",
                "conversion error.",
            ],
            "grade_code_values": max(worst.values()),
            "_grade_why": [
                "MEASURED, not chosen. A tolerance picked to make a test pass leaves a guard that",
                "cannot fail, so this records what the Bench's approximations actually cost.",
                "",
                "WHERE IT COMES FROM, and it is not where it was assumed to be. Decomposed on the",
                "shipped look, worst case in 8-bit code values:",
                "",
                "                 cube    ramp    refs",
                "  tone-only     36.21    2.49   28.69",
                "  trims-only     6.32    2.83    5.08",
                "  shipped       28.81    3.97   23.28",
                "",
                "So the trims are the SMALL half. The Bench's saturation and warmth stand-ins cost",
                "about six code values, and the two partly cancel, which is why `shipped` measures",
                "lower than `tone-only` alone.",
                "",
                "The large half is the tone stage's APPLICATION. On neutral tones the Bench is",
                "faithful to within 2.5 code values, so the curve and its domain are right — and a",
                "separate experiment confirmed ffmpeg curves a FULL-range luma, not a 16-235 one",
                "(the limited-range model measured 16.8 against 2.49). What diverges is saturated",
                "colour: the Bench subtracts one luma delta from all three channels, which drives",
                "already-low channels below zero and clamps them, while the renderer curves the Y",
                "plane and merges the ORIGINAL chroma back. The worst patch, a saturated orange,",
                "goes to 187.7/0.0/0.0 in the Bench against 223.9/25.8/0.0 in the renderer.",
                "",
                "That is ADR 0003 seen from the other side: an equal RGB offset is not what",
                "mergeplanes=0x001112 does. The consequence for the app is concrete — its Metal",
                "preview must curve Y and keep CbCr, not shift RGB — and it is a requirement",
                "measured here rather than assumed.",
            ],
            "grade_worst_by_case": worst,
            "grade_margin_code_values": 0.5,
            "_margin_why": [
                "Each case is asserted against its own number above, plus this margin. Both sides",
                "are deterministic — the same ffmpeg build and the same node — so the margin only",
                "absorbs floating-point jitter. A single global tolerance was the alternative and",
                "it would have let the shipped look drift by the extreme case's hundred code",
                "values while still reporting green.",
            ],
        },
        "cases": cases,
    }
    with open(GOLDEN, "w") as f:
        json.dump(golden, f, indent=1)
        f.write("\n")
    print("\nfloor   %.3f code values (RGB/YUV round-trip)" % floor)
    print("grade   %.3f code values worst across cases" % max(worst.values()))
    print("wrote   %s (%d bytes)" % (os.path.relpath(GOLDEN, ROOT), os.path.getsize(GOLDEN)))


# --- check --------------------------------------------------------------------
def check():
    if not os.path.exists(GOLDEN):
        sys.exit("no golden at %s — run tests/grade-parity.py --regenerate" % GOLDEN)
    golden = json.load(open(GOLDEN))
    fails = []

    # 1. Freshness, by content: the guard that stops a chain edit shipping with a golden that
    #    describes the chain it replaced.
    now = chain_fingerprint()
    if now != golden["chain_fingerprint"]:
        print("STALE GOLDEN\n"
              "  grade_chain in scripts/lib.sh no longer matches the chain this golden was\n"
              "  generated from.\n    golden: %s\n    lib.sh: %s\n"
              "  If the change was intended, re-run tests/grade-parity.py --regenerate and say in\n"
              "  the commit what moved and why." % (golden["chain_fingerprint"][:16], now[:16]),
              file=sys.stderr)
        return 1

    # 2. The probe itself, by content, for the same reason.
    if os.path.exists(PROBE):
        have = hashlib.sha256(open(PROBE, "rb").read()).hexdigest()
        if have != golden["probe"]["sha256"]:
            print("the probe image does not match the golden measured on it", file=sys.stderr)
            return 1

    # 3. The curve on its own, so a curve drift is pinned to the curve rather than to the grade.
    xs = [i / 256.0 for i in range(257)]
    for name, params, _sat, _warm, _look in CASES:
        j, p = js_curve(params, xs), py_curve(params, xs)
        worst = max(abs(a - b) for a, b in zip(j, p))
        if worst > CURVE_TOLERANCE:
            fails.append("curve %s: max delta %.5f > %.5f" % (name, worst, CURVE_TOLERANCE))
            print("DRIFTED  curve %-15s max delta %.5f" % (name, worst))
        else:
            print("in step  curve %-15s max delta %.6f" % (name, worst))

    # 4. The whole grade, against ffmpeg's recorded output.
    base = {c["name"]: c for c in golden["cases"]}["post-look"]["output"]
    ins = [[round(x, 4) for x in to8(v)] for v in base]
    # PER CASE, not against the global worst. The global worst belongs to the `extreme` case, so a
    # single tolerance would let the shipped look drift a hundred code values and still pass — a
    # guard that cannot fail. Each case is pinned to the divergence measured for it, plus a margin
    # for floating-point jitter: both sides are deterministic, so the margin is small on purpose.
    margin = golden["tolerances"]["grade_margin_code_values"]
    per_case = golden["tolerances"]["grade_worst_by_case"]
    for c in golden["cases"]:
        if c["name"] in CALIBRATION:
            continue
        js = js_grade(c["params"], c["saturation"], c["warmth"], ins)
        worst = worst_delta(js, [to8(v) for v in c["output"]])
        tol = per_case[c["name"]] + margin
        if worst > tol:
            fails.append("grade %s: max delta %.3f > %.3f" % (c["name"], worst, tol))
            print("DRIFTED  grade %-15s max delta %.3f (was %.3f, margin %.2f)"
                  % (c["name"], worst, per_case[c["name"]], margin))
        else:
            print("as measured  grade %-15s max delta %.3f" % (c["name"], worst))

    if fails:
        print("\nThe Bench and the renderer have diverged. The browser preview no longer predicts\n"
              "what ffmpeg produces, so any grade sent from it is unreliable until they are\n"
              "reconciled. Fix BOTH, then re-run.\n  " + "\n  ".join(fails), file=sys.stderr)
        return 1
    print("\nCurve within %.5f. Whole grade at its measured divergence per case, floor %.3f."
          % (CURVE_TOLERANCE, golden["tolerances"]["conversion_floor_code_values"]))
    return 0


if __name__ == "__main__":
    if "--regenerate" in sys.argv[1:]:
        regenerate()
        sys.exit(0)
    sys.exit(check())
