import AppKit
import Combine
import GradeKit
import SwiftUI

/// What the interface is editing, and the preview that follows it.
///
/// ObservableObject, not @Observable: the latter is macOS 14 and this builds against 13.
final class GradeModel: ObservableObject {
    @Published var look: Look
    @Published var curve: ToneCurve?
    @Published var previewImage: NSImage?
    /// The previous render, kept for hold-to-compare. Comparing against the last committed frame
    /// is what a colourist actually wants while adjusting: "is this better than what I had".
    @Published var previousImage: NSImage?
    @Published var status: String = ""
    @Published var isRendering = false
    @Published var selectedClip: ClipList.Entry?
    @Published var previewSeconds: Double = 1
    /// The look the visible frame was rendered from. Comparing it with the live one is how the
    /// panel knows the reading is out of date — which matters because this renders on release,
    /// not continuously, so the gap is real.
    @Published private(set) var renderedLook: Look?

    var isStale: Bool {
        guard let rendered = renderedLook, previewImage != nil else { return false }
        return rendered != look
    }

    /// The project: presets, delivery, and what is decided per clip. Held here because the crop
    /// offset has to live somewhere that survives selecting another clip, and because a shoot is
    /// the unit of work rather than a file.
    @Published var project: Project

    /// The cubes on disk, read once: the interface offers what is there.
    let availableLooks: [String]

    let workDirectory: URL

    private let engine: EngineLocation
    private let renderer: PreviewRenderer
    private let queue = DispatchQueue(label: "loggrade.preview")

    init(engine: EngineLocation, look: Look) {
        self.engine = engine
        self.look = look
        self.availableLooks = engine.availableLooks()
        self.project = Project(presets: [.init(name: "shipped", look: look)],
                               activePreset: "shipped")
        let work = FileManager.default.temporaryDirectory
            .appendingPathComponent("loggrade-preview", isDirectory: true)
        self.workDirectory = work
        self.renderer = PreviewRenderer(engine: engine, workDirectory: work)
        refreshCurve()
    }

    /// The curve is regenerated by the engine's own generator, so the graph beside the sliders is
    /// the table the render applies. It costs about a tenth of a second, which is why it can be
    /// done on every change rather than only on release.
    func refreshCurve() {
        let tone = look.tone
        let generator = engine.toneGenerator
        queue.async { [weak self] in
            let curve = try? ToneCurve.generate(using: generator, tone: tone)
            DispatchQueue.main.async { self?.curve = curve }
        }
    }

    /// ON RELEASE, not on every movement. The exact preview is a render through the real chain,
    /// which takes a second or two: firing it per pixel of slider travel would queue work nobody
    /// is waiting for any more. This is the scanner's preview-scan gesture — adjust, then look.
    /// Renders every clip in the list, through the engine, with the project's own settings. The
    /// look is written to a file per run and handed over with LOOK_FILE, so a render never edits
    /// the checkout's own look.json.
    func convert(queue: RenderQueue) {
        guard let clips = clipEntries else { return }
        queue.clearFinished()
        queue.enqueue(clips.map { (url: $0.url, stem: $0.stem) })
        let project = self.project
        let look = self.look
        let work = self.workDirectory
        queue.enqueue([])
        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
            guard let self else { return }
            let lookFile = work.appendingPathComponent("render-look.json")
            try? FileManager.default.createDirectory(at: work, withIntermediateDirectories: true)
            try? look.write(to: lookFile)
            queue.start(environment: { stem in
                var env = project.environment(for: stem, lookFile: lookFile)
                env["GRADE_WORK_DIR"] = work.path
                return env
            })
            _ = self
        }
    }

    func cancel(queue: RenderQueue) {
        queue.cancel()
        RenderQueue.sweepStagingFiles(in: workDirectory)
    }

    /// The clips the interface is holding, set by the window when the list changes.
    var clipEntries: [ClipList.Entry]?

    /// The crop offset for the selected clip, in master pixels. Nil means undecided, which is not
    /// zero: the engine refuses a Feed render across clips without one, because one clip's framing
    /// applied to eighteen others produces files that all look done.
    var cropOffset: Int? {
        get { selectedClip.flatMap { project.clips[$0.stem]?.cropOffset } }
        set {
            guard let stem = selectedClip?.stem else { return }
            var settings = project.clips[stem] ?? Project.ClipSettings()
            settings.cropOffset = newValue
            project.clips[stem] = settings
        }
    }

    /// The window's geometry for the selected clip, from what was measured about it rather than
    /// from this camera's numbers assumed.
    var cropGeometry: CropGeometry? {
        guard let f = selectedClip?.fields else { return nil }
        // The container reports these clips landscape, because rotation is a display-matrix flag.
        // The master the engine crops is the DECODED frame, so the two are swapped here.
        let w = min(f.width, f.height), h = max(f.width, f.height)
        return CropGeometry(sourceWidth: w, sourceHeight: h)
    }

    /// What would stop a render, named before one starts.
    var blockers: [Project.Blocker] {
        project.blockers(for: clipNames)
    }

    var clipNames: [String] = []

    func renderPreview() {
        guard let clip = selectedClip, clip.isUsable else { return }
        let look = self.look
        let seconds = previewSeconds
        isRendering = true
        status = "rendering…"
        queue.async { [weak self] in
            guard let self else { return }
            do {
                let frame = try self.renderer.render(clip: clip.url, seconds: seconds, look: look)
                let image = NSImage(contentsOf: frame.url)
                DispatchQueue.main.async {
                    self.previousImage = self.previewImage
                    self.previewImage = image
                    self.renderedLook = look
                    self.isRendering = false
                    self.status = "grade only — no grain, sharpening, denoise, stabiliser or dither"
                }
            } catch {
                DispatchQueue.main.async {
                    self.isRendering = false
                    self.status = String(describing: error)
                }
            }
        }
    }
}
