import GradeKit
import SwiftUI

/// The chain, in the order it runs, with the input transform pinned at the top.
///
/// Resolve shows a node graph and Baselight a layer stack because the order IS the grade. Here the
/// order is also a measured artefact — corrections before the conversion, tone after the look and
/// on luma only — so showing it makes that legible instead of implied by where panels happen to
/// sit.
struct InspectorView: View {
    @ObservedObject var model: GradeModel

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 18) {
                stage("Apple Log → Rec.709", locked: true) {
                    Text("Apple's conversion. Not a choice: its colour is more accurate than "
                         + "anything hand-rolled, and the cube carries a display rendering Apple "
                         + "has not published. See docs/adr/0002_KEEP_APPLES_CST.md.")
                        .font(.caption).foregroundStyle(.secondary)
                        .fixedSize(horizontal: false, vertical: true)
                }
                stage("correct — before the conversion, in log") {
                    slider("exposure", $model.look.correct.exposure, -3...3, "stops")
                    slider("temperature", $model.look.correct.temp, -1...1)
                    slider("tint", $model.look.correct.tint, -1...1)
                    slider("luminance mix", $model.look.correct.lumMix, 0...1)
                    Text(model.look.correct.isNeutral
                         ? "neutral — the filter is left out of the graph entirely"
                         : "active — generated as a 33-point cube")
                        .font(.caption2).foregroundStyle(.secondary)
                }
                stage("look") {
                    Picker("film emulation", selection: $model.look.lookLUT) {
                        Text("none (neutral)").tag("none")
                        ForEach(model.availableLooks, id: \.self) { name in
                            Text(name).tag(name)
                        }
                    }
                    .onChange(of: model.look.lookLUT) { _ in model.renderPreview() }
                    Text("a look and a tone belong to each other: the shipped curve was tuned "
                         + "with this cube in the chain")
                        .font(.caption2).foregroundStyle(.secondary)
                        .fixedSize(horizontal: false, vertical: true)
                }
                stage("tone — luma only") {
                    HStack(alignment: .top, spacing: 14) {
                        VStack(spacing: 6) {
                            slider("midtone level", $model.look.tone.gamma, 1...2.6)
                            slider("contrast", $model.look.tone.contrast, 0.8...1.8)
                            slider("pivot", $model.look.tone.pivot, 0.25...0.65)
                            slider("shoulder", $model.look.tone.shoulder, 0...0.8)
                            slider("toe", $model.look.tone.toe, 0...0.8)
                            slider("black point", $model.look.tone.black, -0.08...0.08)
                        }
                        CurveView(curve: model.curve).frame(width: 120, height: 120)
                    }
                    Text("the curve is generated by the engine, not drawn from a copy of its maths")
                        .font(.caption2).foregroundStyle(.secondary)
                }
                stage("trims") {
                    slider("saturation", $model.look.colour.saturation, 0.6...1.6)
                    slider("warmth", $model.look.colour.warmth, -0.12...0.12)
                }
                stage("delivery — not in the preview") {
                    slider("grain", $model.look.grainStrength, 0...20)
                    slider("stabiliser smoothing", $model.look.stabilisationSmoothing, 0...60)
                }
            }
            .padding(14)
        }
    }

    private func stage<Content: View>(_ title: String, locked: Bool = false,
                                      @ViewBuilder content: () -> Content) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            HStack(spacing: 6) {
                if locked { Image(systemName: "lock.fill").font(.caption2) }
                Text(title).font(.subheadline.weight(.medium))
            }
            content()
        }
    }

    /// Double-click resets one control, which is what every grading suite does and what a person
    /// reaches for after pushing something too far.
    private func slider(_ label: String, _ value: Binding<Double>,
                        _ range: ClosedRange<Double>, _ unit: String = "") -> some View {
        HStack(spacing: 8) {
            Text(label).font(.caption).frame(width: 96, alignment: .leading)
            Slider(value: value, in: range) { editing in
                if !editing {
                    model.refreshCurve()
                    model.renderPreview()   // on release: a render is seconds, not milliseconds
                }
            }
            Text(String(format: "%.3f", value.wrappedValue) + (unit.isEmpty ? "" : " " + unit))
                .font(.system(.caption2, design: .monospaced))
                .frame(width: 58, alignment: .trailing)
        }
    }
}

/// The tone curve, drawn from the engine's own table.
struct CurveView: View {
    let curve: ToneCurve?

    var body: some View {
        GeometryReader { geo in
            ZStack {
                Path { p in
                    p.move(to: CGPoint(x: 0, y: geo.size.height))
                    p.addLine(to: CGPoint(x: geo.size.width, y: 0))
                }.stroke(Color.secondary.opacity(0.25), lineWidth: 1)
                if let curve {
                    Path { p in
                        let steps = 96
                        for i in 0...steps {
                            let x = Double(i) / Double(steps)
                            let y = curve.value(at: x)
                            let point = CGPoint(x: x * geo.size.width,
                                                y: (1 - y) * geo.size.height)
                            if i == 0 { p.move(to: point) } else { p.addLine(to: point) }
                        }
                    }.stroke(Color.accentColor, lineWidth: 1.6)
                }
            }
            .border(Color.secondary.opacity(0.3))
        }
    }
}

/// The preview, with hold-to-compare against the previous render.
struct PreviewView: View {
    @ObservedObject var model: GradeModel
    @State private var comparing = false

    var body: some View {
        VStack(spacing: 8) {
            ZStack {
                if let image = comparing ? (model.previousImage ?? model.previewImage)
                                          : model.previewImage {
                    Image(nsImage: image).resizable().aspectRatio(contentMode: .fit)
                } else {
                    RoundedRectangle(cornerRadius: 6).fill(.quaternary)
                        .overlay(Text("select a clip, then render a preview")
                            .foregroundStyle(.secondary))
                }
                if model.isRendering {
                    ProgressView().scaleEffect(0.6)
                }
            }
            HStack(spacing: 10) {
                Button("preview") { model.renderPreview() }
                    .disabled(model.selectedClip == nil || model.isRendering)
                Button(comparing ? "showing previous" : "hold to compare") {}
                    .disabled(model.previousImage == nil)
                    .onLongPressGesture(minimumDuration: 0.01, pressing: { comparing = $0 },
                                        perform: {})
                Spacer()
            }
            // Said out loud, always: a preview that silently omits half the chain is output that
            // looks done, which is CONTEXT.md's "squashed" failure in another dimension.
            Text(model.status.isEmpty
                 ? "grade only — no grain, sharpening, denoise, stabiliser or dither"
                 : model.status)
                .font(.caption2).foregroundStyle(.secondary)
                .fixedSize(horizontal: false, vertical: true)
        }
    }
}
