import XCTest
@testable import GradeKit

final class EngineEventTests: XCTestCase {
    private func repoRoot() throws -> URL {
        let here = URL(fileURLWithPath: #filePath)
        guard let engine = EngineLocation.discover(from: here.deletingLastPathComponent()) else {
            throw XCTSkip("no engine checkout above \(here.path)")
        }
        return engine.root
    }

    /// The recorded stream, which is the contract. It is generated by
    /// tests/make-event-fixture.sh and checked against the live engine by the bats suite, so this
    /// test needs no ffmpeg, no footage and no render.
    func testParsesTheRecordedStream() throws {
        let fixture = try repoRoot().appendingPathComponent("tests/fixtures/events.jsonl")
        let text = try String(contentsOf: fixture, encoding: .utf8)
        var events: [EngineEvent] = []
        for line in text.split(separator: "\n", omittingEmptySubsequences: true) {
            if let event = try EngineEvent.decode(line: String(line)) { events.append(event) }
        }
        XCTAssertEqual(events.map(\.name),
                       ["disk", "run_start", "stabilisation", "clip_planned", "clip_skipped",
                        "run_done"],
                       "the recorded stream's shape is the contract the interface is built on")

        let start = try XCTUnwrap(events.first { $0.name == "run_start" })
        XCTAssertEqual(start.int("clips"), 2)
        XCTAssertEqual(start.double("saturation"), 1.27)

        let planned = try XCTUnwrap(events.first { $0.name == "clip_planned" })
        XCTAssertEqual(planned.clip, "TALL")
        // The placeholder that broke the emitter once: MATCH=0 leaves YAVG a literal "-", which a
        // laxer emitter wrote as a bare number and produced invalid JSON on that one path.
        XCTAssertEqual(planned.string("yavg"), "-")

        let skipped = try XCTUnwrap(events.first { $0.name == "clip_skipped" })
        XCTAssertEqual(EngineCode(rawValue: skipped.string("code") ?? ""), .notPortrait)

        let done = try XCTUnwrap(events.last)
        XCTAssertEqual(done.name, "run_done", "a consumer needs to know the run ended")
        XCTAssertEqual(done.int("skipped"), 1)
    }

    func testZeroAndOneStayNumbers() throws {
        // Foundation bridges a JSON 0 or 1 to Bool, so a decoder that checks Bool first turns
        // every count in the stream into a boolean and every int() on them into nil. That is what
        // the first version of this decoder did, and what run_done's own fields exposed.
        let event = try XCTUnwrap(try EngineEvent.decode(line:
            #"{"event":"run_done","rendered":1,"skipped":0,"failed":0,"dry":1}"#))
        XCTAssertEqual(event.int("rendered"), 1)
        XCTAssertEqual(event.int("skipped"), 0)
        XCTAssertEqual(event.int("dry"), 1)
        XCTAssertEqual(event.fields["rendered"], .number(1))
        XCTAssertNotEqual(event.fields["rendered"], .bool(true))
        // A real boolean, if the engine ever emits one, still decodes as one.
        let flagged = try XCTUnwrap(try EngineEvent.decode(line:
            #"{"event":"x","ok":true}"#))
        XCTAssertEqual(flagged.fields["ok"], .bool(true))
    }

    func testAnUnknownEventSurvivesRatherThanVanishing() throws {
        let event = try XCTUnwrap(try EngineEvent.decode(line:
            #"{"event":"something_new","clip":"IMG_0001","depth":10}"#))
        XCTAssertEqual(event.name, "something_new")
        XCTAssertEqual(event.clip, "IMG_0001")
        XCTAssertEqual(event.int("depth"), 10)
    }

    func testMalformedLinesAreSurfacedNotSwallowed() {
        XCTAssertThrowsError(try EngineEvent.decode(line: "disk OK: 21GB available")) { error in
            XCTAssertEqual(error as? EngineEvent.DecodeFailure,
                           .notJSON(line: "disk OK: 21GB available"))
        }
        XCTAssertThrowsError(try EngineEvent.decode(line: #"{"clip":"IMG_0001"}"#)) { error in
            guard case .noEventName = error as? EngineEvent.DecodeFailure else {
                return XCTFail("an object with no event name should say so, got \(error)")
            }
        }
        XCTAssertNil(try? EngineEvent.decode(line: "   "), "a blank line is not a failure")
    }

    /// A contract test across two languages: every code the engine can emit must have a case here,
    /// or the interface shows a raw string where it should show a sentence.
    func testEveryCodeTheEngineEmitsIsKnown() throws {
        let root = try repoRoot()
        var emitted = Set<String>()
        for script in ["scripts/grade.sh", "scripts/lib.sh", "scripts/03-final.sh"] {
            let text = try String(contentsOf: root.appendingPathComponent(script), encoding: .utf8)
            let pattern = try NSRegularExpression(pattern: #"emit_code ([A-Z_]+)"#)
            for match in pattern.matches(in: text, range: NSRange(text.startIndex..., in: text)) {
                if let range = Range(match.range(at: 1), in: text) {
                    emitted.insert(String(text[range]))
                }
            }
        }
        XCTAssertFalse(emitted.isEmpty, "found no emit_code calls, so this test proves nothing")
        for raw in emitted.sorted() {
            if case .unknown = EngineCode(rawValue: raw) {
                XCTFail("the engine emits \(raw) and EngineCode does not know it")
            }
        }
    }
}
